name: bizops
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  bloc: ^9.2.0
  get_it: ^9.2.0
  injectable: ^2.7.1+4

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4

  flutter_lints: ^6.0.0
  bloc_test: ^10.0.0

flutter:
  uses-material-design: true

